# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f21b8dd0ac569e80737dcd6f018f565ab125112829c94f872e93d3087167ef637924d7243b92a6a98f1b44b861f0b536bc634f1a40db8a3115532a4a33eaa9e3

test:
  secret_key_base: ed0a48b9a8a2eacf8c7f9fa68af107567e3f7468f66c4a92be6e986d73f706020b15e98f5523a584a8e38e598459f991df98e419e938717597e34ae8152b3199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
